{application,via_utils,
             [{applications,[kernel,stdlib,elixir,logger,ring_logger,
                             circuits_uart]},
              {description,"Utility functions build for use with the Via autopilot."},
              {modules,['Elixir.ViaUtils.Comms',
                        'Elixir.ViaUtils.Comms.Supervisor',
                        'Elixir.ViaUtils.Constants','Elixir.ViaUtils.Enum',
                        'Elixir.ViaUtils.File','Elixir.ViaUtils.Format',
                        'Elixir.ViaUtils.Helper.DiscreteLooper.GenServer',
                        'Elixir.ViaUtils.Helper.Process.GenServer',
                        'Elixir.ViaUtils.Helper.Test',
                        'Elixir.ViaUtils.Location','Elixir.ViaUtils.Math',
                        'Elixir.ViaUtils.Motion','Elixir.ViaUtils.Process',
                        'Elixir.ViaUtils.Registry','Elixir.ViaUtils.Uart',
                        'Elixir.ViaUtils.Watchdog']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
