{application,ring_logger,
             [{applications,[kernel,stdlib,elixir,logger,circular_buffer]},
              {description,"A ring buffer backend for Elixir Logger with IO streaming"},
              {modules,['Elixir.RingLogger','Elixir.RingLogger.Autoclient',
                        'Elixir.RingLogger.Client',
                        'Elixir.RingLogger.Client.State',
                        'Elixir.RingLogger.Server',
                        'Elixir.RingLogger.Server.State']},
              {registered,[]},
              {vsn,"0.8.2"}]}.
